### ISSUE TITLE
Flagged as trojan by antivirus

### ISSUE THREAD

**Issue by claabs** [akiver/cs-demo-analyzer#4]
### Describe the bug

`csda.exe` is flagged by Windows as [Trojan:Win32/Wacatac.B!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.B!ml&threatid=2147735505). Here's the [VirusTotal analysis](https://www.virustotal.com/gui/file/54f4b1dcb36f706edc88e74cc162bf3fa23bb76fa6aac183b6802d123b571e49/detection) as well.

I'm sure it's a false positive, just raising awareness of the issue.

### Steps to reproduce

1. Download and unzip on Windows
2. Check Windows Security protection history

### Expected behavior

It does not get quarantined by Windows Security.

### Environment information

- Version: 1.0.3
- OS: Windows 11 23H2

**Comment by akiver** [comment]
I just submitted the binary to MS for "Incorrectly detected as potentially unwanted application" - will see.
Code signing is not an option as it's expensive.

Binaries are built and uploaded from a GitHub action, and you can build it from the sources if you want to.

**Comment by akiver** [comment]
From the MS report, it's not detected as a malware:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications.

![s](https://github.com/akiver/cs-demo-analyzer/assets/1842524/f42c166c-5722-4792-9132-6526f761b800)

I'm closing it - it's the only thing I could do about it.
